### ISSUE TITLE
latex sources

### ISSUE THREAD

**Issue by LeanderK** [APMLA/apmla_material#2]
I don't know if the original sources are latex-files, but if you could upload them to the repo. This would enable us students to create pull-request if we found something confusion or too short.

At my old university KIT we had some lectures that did this and it got a steady stream of improvements from students, but of course it also introduces some overhead for you because you have to review to check that our changes are correct. It's just a suggestion!

**Comment by ivaleraM** [comment]
As discuss in class, we'll not share the latex files but we encourage you to create your own and more complete version of the notes.
