### ISSUE TITLE
[Tutorial 2, Exercise 1] Task not 100% clear

### ISSUE THREAD

**Issue by julianstastny** [APMLA/apmla_material#4]
In Exercise 1a, we are asked to derive "the" expression for the log joint distribution, but I wonder how detailed the expression should be. For example, do we have to expand the expression for the categorical distribution in terms of Words and Dictionaries?

I have the same question about 1b, since "closed-form" solution is kind of a vague term.

Thank you!

**Comment by psanch21** [comment]
Hi,

You should expand the expressions as much as possible, therefore you should expand the formulas of all the distributions involved. This applies to all the expressions in Exercise 1.

Hope this helps!

**Comment by julianstastny** [comment]
It does, thanks! Closing because the universe will explode if resolved issues stay open
